# Generated by Django 3.0.6 on 2020-05-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='star',
            new_name='rate',
        ),
    ]
